### ISSUE TITLE
"Project" is specific to BC Stats

### ISSUE THREAD

**Issue by cwickham** [cwickham/r_intro_bc_stats#3]
Both Data Transform and Vis end with a "Project" section.  This project was specifically chosen for the original audience, people in the BC Stats group, using data and a report they produce.  

@cdhowe and @teonbrooks are most affected.  I think the options are:
1. Drop these sections entirely.
2. Choose a new example and tailor to this audience
3. Use the sections as is.

Given how close we are, and our time constraints on the day, I'd vote for 1.  The .Rmd for these sections stop before the "Project" section, so that route only involves deleting some slides.

**Comment by cwickham** [comment]
Actually it doesn't look like this _is_ in "Transform", just "Visualize"

**Comment by cdhowe** [comment]
I was just looking at that section, and I agree. It will help with our time crunch.
